<?php

namespace App\Filament\Resources\BudgetResource\Pages;

use App\Filament\Resources\BudgetResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateBudget extends CreateRecord
{
    protected static string $resource = BudgetResource::class;

//    protected function handleRecordCreation(array $data): Model
//    {
//        dd($data);
//        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
//    }
}
